# Generated by Django 3.1.4 on 2021-01-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_and_number', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=80)),
                ('zipcode', models.CharField(max_length=30)),
                ('additional_info', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='farm',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.address'),
        ),
    ]
